### PR TITLE
add SHA256 script

### PR DESCRIPTION
**Pull request by zktoy**
I follow [SHA256 algorithm](https://github.com/natfoam/lib/blob/main/sha2-compress/src/lib.rs#L169) step by step, and realize a SHA256 script.
It works for data within 60 bytes right now, and there are two examples `test_sha256_empty` and `test_sha256_helloworld`.

I realize the rrotx as a combination of existing fn, such as:
```
/// Right rotation of an u32 element by 18 bits
pub fn u32_rrot18() -> Script {
  script! {

    {u32_rrot16()} //16+16+16+2=50 mod 32=18
    {u32_rrot16()}
    {u32_rrot16()}
    {u32_rrot2()}
  }
}
```

I can't manage the `env` well right now, so the `save_wi16_swap` is a little native:
```
fn save_wi16_swap(env: &mut Env, m: Ptr, delta: u32) -> Script {
    let n = env.ptr(m) + delta;

    let script = script!(
        for _ in 0..(n-1){
            {u32_roll(1)}
            {u32_toaltstack()}
        }
        //drop the specific element
        {u32_roll(1)}
        {u32_drop()}
        //put back others
        for _ in 0..(n-1){
            {u32_fromaltstack()}
        }
    );
    script
}
```

All these can be further optimized.

### CODE REVIEW

**Comment by zktoy** [comment]
I do a rough comparison with [PR54](https://github.com/BitVM/BitVM/pull/54):
| PR | commit id|testcase|script size|max_nb_stack_items|
|---|--|--|--|--|
|[PR54](https://github.com/BitVM/BitVM/pull/54)|[commit 2d8dc5e](https://github.com/wz14/BitVM/commit/2d8dc5efb78c5277b201438ef51dfdbee730251c) | [test_sha256](https://github.com/wz14/BitVM/blob/add_sha256/src/hash/sha256.rs#L442)|1678578|920|?|?|?|
|[this](https://github.com/BitVM/BitVM/pull/57)|[commit 2039084](https://github.com/zktoy/BitVM/commit/2039084542c2e9769b6ce7eedd5c2e9c1090e969)|[test_sha256_helloworld](https://github.com/zktoy/BitVM/blob/sha256_script/src/hash/sha256.rs#L719)|901783|676|
||||**Improved about 46%**|**Improved about 26%**|

**Comment by wz14** [comment]
Hi, zktoy. I'm trying to learn something from this implementation, but I really have some doubts here.

1. In the [test_sha256_helloworld](https://github.com/zktoy/BitVM/blob/sha256_script/src/hash/sha256.rs#L719) test case, why sha256('hello_world') is `b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9`. I just run below command in a linux.
```
echo -n 'hello_world' | sha256sum
35072c1ae546350e0bfa7ab11d49dc6f129e72ccd57ec7eb671225bbd197c8f1 
```
It seems that this implementation has some different with the standard command? Did I miss something?

2. In the comparsion table , the test case [test_sha256](https://github.com/wz14/BitVM/blob/add_sha256/src/hash/sha256.rs#L442) actually run both sha256(80byte) and sha256(32byte), while [test_sha256_helloworld](https://github.com/zktoy/BitVM/blob/sha256_script/src/hash/sha256.rs#L719) run sha256(11byte). What is the baseline for this comparsion?

3. Why not use the rrot in the main branch? That would be shorter than the combination of existing functions. By the way, from my point, using shorter script to implement rrot may be a way to improve the cost of sha256.

Sincerely looking forward to your reply.

**Comment by zktoy** [comment]
Hi, I optimize the 1 block SHA256 from 901783 to 802455, and achieve more **reflexible SHA256 for any size.**

For 1 block size to SHA256:
| PR | commit id|testcase|script size|max_nb_stack_items|
|---|--|--|--|--|
|[PR54](https://github.com/BitVM/BitVM/pull/54)|[commit 2d8dc5e](https://github.com/wz14/BitVM/commit/2d8dc5efb78c5277b201438ef51dfdbee730251c) | [test_sha256](https://github.com/wz14/BitVM/blob/add_sha256/src/hash/sha256.rs#L442)|1678578|920|
|[this](https://github.com/BitVM/BitVM/pull/57)|[commit 9b1d706](https://github.com/zktoy/BitVM/commit/9b1d7061f843e605b82e5913a8c425dff3751eb9)|[test_sha256_1_block](https://github.com/zktoy/BitVM/blob/sha256_script/src/hash/sha256.rs#L719)|802455|676|
||||**Improved about 53%**|**Improved about 26%**|

For 2 block size to SHA256:
| PR | commit id|testcase|script size|max_nb_stack_items|
|---|--|--|--|--|
|[PR54](https://github.com/BitVM/BitVM/pull/54)|[commit 2d8dc5e](https://github.com/wz14/BitVM/commit/2d8dc5efb78c5277b201438ef51dfdbee730251c) | [test_sha256](https://github.com/wz14/BitVM/blob/add_sha256/src/hash/sha256.rs#L442)|1678578?|920?|
|[this](https://github.com/BitVM/BitVM/pull/57)|[commit 9b1d706](https://github.com/zktoy/BitVM/commit/9b1d7061f843e605b82e5913a8c425dff3751eb9)|[test_sha256_2_block](https://github.com/zktoy/BitVM/blob/sha256_script/src/hash/sha256.rs#L873)|1603811|740|

For 3 block size to SHA256:
| PR | commit id|testcase|script size|max_nb_stack_items|
|---|--|--|--|--|
|[PR54](https://github.com/BitVM/BitVM/pull/54)|[commit 2d8dc5e](https://github.com/wz14/BitVM/commit/2d8dc5efb78c5277b201438ef51dfdbee730251c) | [test_sha256](https://github.com/wz14/BitVM/blob/add_sha256/src/hash/sha256.rs#L442)|?|?|
|[this](https://github.com/BitVM/BitVM/pull/57)|[commit 9b1d706](https://github.com/zktoy/BitVM/commit/9b1d7061f843e605b82e5913a8c425dff3751eb9)|[test_sha256_3_block](https://github.com/zktoy/BitVM/blob/sha256_script/src/hash/sha256.rs#L914)|2405256|804|

**Comment by zktoy** [comment]
> Hi, zktoy. I'm trying to learn something from this implementation, but I really have some doubts here.
> 
> 1. In the [test_sha256_helloworld](https://github.com/zktoy/BitVM/blob/sha256_script/src/hash/sha256.rs#L719) test case, why sha256('hello_world') is `b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9`. I just run below command in a linux.
> 
> ```
> echo -n 'hello_world' | sha256sum
> 35072c1ae546350e0bfa7ab11d49dc6f129e72ccd57ec7eb671225bbd197c8f1 
> ```
> 
> It seems that this implementation has some different with the standard command? Did I miss something?
> 
> 2. In the comparsion table , the test case [test_sha256](https://github.com/wz14/BitVM/blob/add_sha256/src/hash/sha256.rs#L442) actually run both sha256(80byte) and sha256(32byte), while [test_sha256_helloworld](https://github.com/zktoy/BitVM/blob/sha256_script/src/hash/sha256.rs#L719) run sha256(11byte). What is the baseline for this comparsion?
> 3. Why not use the rrot in the main branch? That would be shorter than the combination of existing functions. By the way, from my point, using shorter script to implement rrot may be a way to improve the cost of sha256.
> 
> Sincerely looking forward to your reply.

Sorry, I don't have a Linus OS. Maybe [SHA256() doesn't match sha256sum](https://groups.google.com/g/cryptopp-users/c/kTaH62MAuys) will be useful?
And I add a more flexible testcase: [test_sha256_1_block](https://github.com/zktoy/BitVM/blob/sha256_script/src/hash/sha256.rs#L719):
```
#[test]
    fn test_sha256_3_block() {
        //3 block size
        let s = String::from("hello world hello world hello world hello world hello world hello world hello world hello world hello world hello world hello world hello world hello world hello world hello world");
        //2 block size
        //let s = String::from("hello world hello world hello world hello world hello world");
        //1 block size
        //let s = String::from("hello world");
        
        let mut hasher = Sha256::new();
        hasher.update(s.clone());
        // Note that calling `finalize()` consumes hasher
        let expected_hash = hasher.finalize();
        println!("Expected hash: {:x}", expected_hash);

        // change [u8] to [u32]
        let mut hash_out: Vec<u32> = Vec::new();
        let hash_u8_array: Vec<&[u8]> = expected_hash.chunks(4).collect();
        for i in 0..hash_u8_array.len() {
            let b = hex::encode(&hash_u8_array[i]);
            hash_out.extend([(i64::from_str_radix(&b, 16).unwrap()) as u32 ])
        }

        let input = s.into_bytes();

        let message = pad(input);
        let msg_len = message.len() * 8; // multiply 8 for is u8 vector
        assert_eq!( msg_len % 512, 0);
        let chunk_size = (msg_len / 512) as u32;
        let script = script! {
            {sha256(chunk_size, &mut message.clone(), & message)}
            for i in 0..8{
                {u32_push(hash_out[i])}
                {u32_equalverify()}
            }
            OP_TRUE
        };
        let res = execute_script(script);
        assert!(res.success);
    }
```

**Comment by zktoy** [comment]
SHA256() will split the padded message into 512-bit blocks, though here 'block' is not the 'Bitcoin block'.
To avoid confusion. I'll rename the 512-bit block as 'chunk'.
I add a **[test_sha256_blockhash()]**(https://github.com/zktoy/BitVM/blob/sha256_script/src/hash/sha256.rs#L854) test case to show that this realization is correct. 
I add a `repeated_count` in my `sha256(chunk_size: u32, message: &[u8], repeated_count: u32)` func, and while setting `repeated_count=2`, it's just `SHA256(SHA256(m))`, if  `repeated_count=3`, then `SHA256(SHA256(SHA256(m)))`. It's very flexible.

For `SHA256(SHA256(block_header))` case, it's corresponding to **3** chunk compression. 
**Right now, I improve 1 chunk compression script size from 802455 to 568775.** 

And `SHA256(SHA256(block_header))` script size is almost 3 times of one chunk script size

**Comment by RobinLinus** [comment]
Does your implementation now pass the tests of @wz14's implementation?

**Comment by zktoy** [comment]
> Does your implementation now pass the tests of @wz14's implementation?

Yes, of course. Just as shown in [test_sha256_blockhash](https://github.com/zktoy/BitVM/blob/sha256_script/src/hash/sha256.rs#L819).

I've done some optimization, for `SHA256(SHA256(block_header))` case:
| PR | commit id|testcase|script size|max_nb_stack_items|
|---|--|--|--|--|
|[PR54](https://github.com/BitVM/BitVM/pull/54)|[commit 2d8dc5e](https://github.com/wz14/BitVM/commit/2d8dc5efb78c5277b201438ef51dfdbee730251c) | [test_genesis_block](https://github.com/wz14/BitVM/blob/add_sha256/src/hash/sha256.rs#L442)|1676298|920|
|[this](https://github.com/BitVM/BitVM/pull/57)|[commit f3cd7de](https://github.com/zktoy/BitVM/commit/f3cd7deeddf581f4144b09b49daa75164cd79974)|[test_sha256_blockhash](https://github.com/zktoy/BitVM/blob/sha256_script/src/hash/sha256.rs#L819)|1552353|732|
||||**Improved about 7.4%**|**Improved about 20.4%**|

**Comment by RobinLinus** [comment]
We went with the other implementation. Thanks for the submission!

**Pull request closed without merging**
