### PR TITLE
[fflonk's verifier] assembling the individual scripts

### PR DESCRIPTION
**Pull request by zulunetwork-dev**
Hi, 

We've implemented the fflonk's verifier with the updated pairing verification work #68 based on [On Proving Pairings](https://eprint.iacr.org/2024/640.pdf), and the relevant tests passed.

Main contribution is the assembling script `verifier.rs` under `fflonk` folder.

Few figures for this:
- the total script size is approximately 7.4G
- number of public input is 2
- the maximum stack height is 905

Our team members including @[SuccinctPaul](https://github.com/SuccinctPaul), @[peinlcy](https://github.com/peinlcy), our team leader @[Cyimon](https://github.com/Cyimon), and @PayneJoe . We would especially like to thank the https://eprint.iacr.org/2024/640.pdf

### CODE REVIEW

**Comment by weikengchen** [comment]
A very good next step (also needed) is to pass over variables between the individual scripts (since they are actually not constant)

**Comment by weikengchen** [comment]
(how long does the execution take if I may ask)

**Comment by zulunetwork-dev** [comment]
> (how long does the execution take if I may ask)

2100 seconds or so

**Comment by lucidLuckylee** [comment]
Amazing work! Thank you!
I removed the second rust-bitcoin-scriptexec dependency in #70. The stack limit can now be ignored by setting the `enforce_stack_limit` option to false in our [bitVM/rust-bitcoin-scriptexec](https://github.com/BitVM/rust-bitcoin-scriptexec/).
I kept your history so if you are fine with that I'll merge #70 instead and close this one.

**Comment by zulunetwork-dev** [comment]
> Amazing work! Thank you! I removed the second rust-bitcoin-scriptexec dependency in #70. The stack limit can now be ignored by setting the `enforce_stack_limit` option to false in our [bitVM/rust-bitcoin-scriptexec](https://github.com/BitVM/rust-bitcoin-scriptexec/). I kept your history so if you are fine with that I'll merge #70 instead and close this one.

Certainly, thanks Lukas -)

**Comment by soheltaj7** [comment]
zulu-network:fflonk/verifier-01

**Pull request closed without merging**
